- name: Install and start Apache HTTPD
  hosts: web
  tasks:
    - name: httpd package is present
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    
    - name: correct index.html is present
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
    
    - name: httpd is started
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true